### ISSUE TITLE
README, where to purchase switches

### ISSUE THREAD

**Issue by paulywill** [ellie-long/Zoom-Control-Panel#1]
I really like the buttons recommended.

Where do you recommend to purchase?

**Comment by ellie-long** [comment]
I had picked them up a long time ago on Amazon for a KSP controller that never got built. I think it was these in various colors, some latching, some momentary: https://www.amazon.com/gp/product/B01N6FZZ0E/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1

And this for the mushroom, removed from the box it came in: https://www.amazon.com/URBEST-Momentary-Mushroom-Position-Rotary/dp/B01M0K8XY6/ref=sr_1_5?dchild=1&keywords=mushroom+button&qid=1612559296&s=industrial&sr=1-5

**Comment by paulywill** [comment]
Amazing!
Thanks for answering this BTW! Much appreciated!!

**Comment by ellie-long** [comment]
The icons are in the github -- I printed them on sticker paper and attached them on the buttons under the colored plastic bits
